Refactoring architecture once more - To enable better handling of other types of responses other than sendMessage - Adding intentional failed UT to verify CI

diff --git a/test/pytest b/test/pytest
--- a/test/pytest
+++ b/test/pytest
@@ -1,4 +1,7 @@
 #!/bin/bash
-cd test
-python3 -m unittest *.py
-cd ..
+python3 -m unittest test/*.py
+if [ $? -ne 0 ]
+then
+    echo "=== Test Failed! ==="
+    exit 1
+fi
