Architecture refactor #2 (Bot v3) (#6)
* Refactoring architecture once more
- To enable better handling of other types of responses other than sendMessage
- removing ALLOW_EDITED_MESSAGES flag in config
- adding format_json_response method for better flow

diff --git a/test/pytest b/test/pytest
--- a/test/pytest
+++ b/test/pytest
@@ -1,4 +1,7 @@
 #!/bin/bash
-cd test
-python3 -m unittest *.py
-cd ..
+python -m unittest discover -s test -p "*_test.py"
+if [ $? -ne 0 ]
+then
+    echo "=== Test Failed! ==="
+    exit 1
+fi
